services:
  defo:
    image: nginx:1.21.5
    requires:
      - mysql
  rwc:
    image: nginx:1.21.5
    requires:
      - mysql
  mysql:
    image: nginx:1.21.5
    requires:
      - some_nginx
      - another_nginx
  some_nginx:
    image: nginx:1.21.5
  another_nginx:
    image: nginx:1.21.5
  somethng:
    image: nginx:1.21.5
control_plane:
  host: nest.example.com
proxy:
  http: 8081
  https: 8443
  self_signed: true
